In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/content/students.csv')

In [3]:
data.shape

(186, 48)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [ ]:
data['Weight'][9]

data[['Weight', 'Sex']].loc[9]

Weight       58.0
Sex       женский
Name: 9, dtype: object

In [ ]:
#df['Hostel'].value_counts()

In [ ]:
data.query('Weight == 120').Growth

7    180
Name: Growth, dtype: int64

In [ ]:
data.Weight.max()

120.0

In [ ]:
data['Army'][0:15]

0     не призовут (по разным причинам)
1     не призовут (по разным причинам)
2                       могут призвать
3     не призовут (по разным причинам)
4     не призовут (по разным причинам)
5                       могут призвать
6     не призовут (по разным причинам)
7                       могут призвать
8     не призовут (по разным причинам)
9     не призовут (по разным причинам)
10    не призовут (по разным причинам)
11                      могут призвать
12    не призовут (по разным причинам)
13    не призовут (по разным причинам)
14                      могут призвать
Name: Army, dtype: object

In [ ]:
 army_persons = data[data['Army'] == 'могут призвать']

In [ ]:
army_persons['Hair length'].mean()

11.045945945945945

In [ ]:
data[data['Friend number'] == 0].value_counts('Sex')

Sex
женский    1
мужской    1
dtype: int64

In [ ]:
dor_lovers = data[data['Animal'] == 'Собак']

In [ ]:
sum(dor_lovers['Floor number'] == 1)/len(dor_lovers) * 100

11.666666666666666

In [5]:
data['Brother-sister'].value_counts()

есть брат                 62
есть сестра               55
нет ни брата ни сестры    39
есть и брат и сестра      30
Name: Brother-sister, dtype: int64

In [7]:
single_child = data[data['Brother-sister'] == 'нет ни брата ни сестры']

In [9]:
not_single_child = data[data['Brother-sister'] != 'нет ни брата ни сестры']

In [15]:
 single_child['Social network duration min'].median() -   not_single_child['Social network duration min'].median()

60.0

In [16]:
data['Fastfood'].value_counts()

KFC                                                82
Бургер кинг                                        56
Макдональдс (или как он там сейчас называется?)    48
Name: Fastfood, dtype: int64

In [18]:
KFC_persons = data[data['Fastfood'] == 'KFC']

In [19]:
Burger_persons = data[data['Fastfood'] == 'Бургер кинг']

In [21]:
Mac_persons = data[data['Fastfood'] == 'Макдональдс (или как он там сейчас называется?)']

In [22]:
KFC_persons['Weight'].mean() - Mac_persons['Weight'].mean()

8.059154929577474

Из имеющейся таблицы с анкетами наших студентов создайте "обрезанную таблицу" df_cut, состоящую из столбцов "Год рождения", "Рост", "Вес", "Длина волос", "Размер обуви".

Отсортируйте таблицу по возрастанию признака "Размер обуви". В ответ напишите год рождения студента, попавшего в первую строку отсортированной таблицы.

In [25]:
data1 = data[['Year of birth', 'Growth', 'Weight', 'Hair length', 'Shoe size']]

In [26]:
data1.sort_values('Shoe size')

     Year of birth  Growth  Weight  Hair length  Shoe size
96            2003     163    56.0         50.0         34
47            2004     159     NaN         25.0         35
52            2002     163    53.0         55.0         35
37            1997     158    60.0         60.0         35
10            2001     158    47.0         50.0         35
..             ...     ...     ...          ...        ...
20            2001     186    93.0         20.0         45
8             2002     185    69.0         25.0         46
103           2002     197   100.0         23.0         46
7             2003     180   120.0         20.0         48
27            2003     193    61.0          3.0         48

[186 rows x 5 columns]

Отсортируйте таблицу по убыванию признака "Размер обуви". В ответ напишите год рождения студента, попавшего в третью строку отсортированной таблицы.

In [34]:
data1_sort = data1.sort_values(['Shoe size', 'Growth'], ascending = [True, True])

In [35]:
data1_sort.iloc[2, 0]

2001

Отсортируйте таблицу по возрастанию признака "Размер обуви", а внутри группы студентов с одинаковым размером обуви сортировка должна производиться по возрастанию  признака "Рост".

В ответ напишите год рождения студента, попавшего в девятую строку отсортированной таблицы.

In [36]:
data1_sort.iloc[8, 0]

1999

Отсортируйте таблицу по возрастанию признака "Размер обуви", а внутри группы студентов с одинаковым размером обуви сортировка должна производиться по убыванию признака "Рост".

В ответ напишите год рождения студента, попавшего во вторую строку отсортированной таблицы.

In [37]:
data2_sort = data1.sort_values(['Shoe size', 'Growth'], ascending = [True, False])

In [39]:
data2_sort.iloc[1, 0]

2002

Отсортируйте таблицу по убыванию признака "Размер обуви", а внутри группы студентов с одинаковым размером обуви сортировка должна производиться по возрастанию  признака "Рост".

В ответ напишите год рождения студента, попавшего во вторую строку отсортированной таблицы.

In [41]:
data3_sort = data1.sort_values(['Shoe size', 'Growth'], ascending = [False, True])

In [42]:
data3_sort.iloc[1, 0]

2003

Допустим, что все студенты решили сделать себе прически типа "Ирокез".

Создайте новый столбец с названием 'Full length' ("Полный рост"), значения в котором равны сумме роста и длины волос.

Чему равно максимальное значение признака "Полный рост" для наших студентов?

In [43]:
data1['Full length'] = data1['Growth'] + data1['Hair length']

<ipython-input-43-dfa35837349c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['Full length'] = data1['Growth'] + data1['Hair length']

In [45]:
data1['Full length'].max()

319.0

Выведите на экран таблицу со значениями коэффициента корреляции (КК).

Чему равен КК для признаков "Рост" и "Размер обуви"? Ответ округлить до двух знаков после запятой.

In [47]:
data1.corr().round(2)

,Year of birth,Growth,Weight,Hair length,Shoe size,Full length
Year of birth,1.00,-0.11,0.01,0.10,-0.11,0.06
Growth,-0.11,1.00,0.54,-0.55,0.86,-0.24
Weight,0.01,0.54,1.00,-0.32,0.59,-0.15
Hair length,0.10,-0.55,-0.32,1.00,-0.57,0.94
Shoe size,-0.11,0.86,0.59,-0.57,1.00,-0.31
Full length,0.06,-0.24,-0.15,0.94,-0.31,1.00

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [49]:
data.groupby('Glasses')['Russian rating', 'Maths rating'].mean()

<ipython-input-49-a5f6cf5fc36f>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  data.groupby('Glasses')['Russian rating', 'Maths rating'].mean()

                                     Russian rating  Maths rating
Glasses
да                                        83.388235     56.741176
нет                                       80.471910     59.955056
простите. не увидел(а) вопроса ))))       77.900000     54.700000

In [51]:
data.groupby('Rock paper scissors')['Russian rating', 'Maths rating'].mean().round(2)

<ipython-input-51-9660e15d5856>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  data.groupby('Rock paper scissors')['Russian rating', 'Maths rating'].mean().round(2)

                     Russian rating  Maths rating
Rock paper scissors
Бумага                        76.47         52.89
Камень                        81.45         62.17
Ножницы                       83.99         57.74